services:
  react:
    build: react
    image: react-image
    container_name: react-container
    ports:
      - "5173:5173"
    volumes:
      - react-volume:/home/frontend/src
    command: bash -c "npm run dev -- --host 0.0.0.0 --port 5173"
    restart: always
    networks:
      - mynetworks

  django:
    build: django
    image: django-image
    container_name: django-container
    ports:
      - "8000:8000"
    volumes:
      - django-volume:/home/env/backend
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    networks:
      - mynetworks
      
volumes:
  react-volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/react/frontend
      o: bind
      
  django-volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/django/backend
      o: bind

networks:
  mynetworks:
    driver: bridge
